### ISSUE TITLE
Generated infrastructure has incomplete proofs

### ISSUE THREAD

**Issue by b-studios** [plclub/lngen#4] opened 2020-11-22 18:28 UTC
Experimenting with lngen I enountered the following problem: Using three different binders results in infrastructure code that contains incomplete proofs.

Here is the full example:

```
metavar effvar, r ::= {{ repr-locally-nameless }}
metavar expvar, x ::= {{ repr-locally-nameless }}
metavar typvar, X ::= {{ repr-locally-nameless }}

grammar

eff, R :: eff_ ::=
  | top                ::  :: top
  | r                  ::  :: var
  | R1 <+> R2          :: :: dummy

typ, T, S :: 'typ_' ::=
  | base               ::   :: base
  | X                  ::   :: var
  | R T                ::   :: eff

exp, e, f, g :: 'exp_' ::=
  | x                  ::   :: var
  | \ x : T . e        ::   :: abs  (+ bind x in e +)
  | \ r . e            ::   :: rabs (+ bind r in e +)
  | \ X . e            ::   :: tabs (+ bind X in e +)

substitutions
  single e x :: subst_ee

  single T X :: subst_tt
  single e X :: subst_te

  single R r :: subst_rr
  single T r :: subst_rt
  single e r :: subst_re


freevars
  e x  :: fv_ee

  T X  :: fv_tt
  e X  :: fv_te

  R r  :: fv_rr
  T r  :: fv_rt
  e r  :: fv_re
```

the commands that I use to generate the coq code:
```
ott -coq_lngen true -i bug.ott -o bug.v
lngen --coq-ott bug --coq bug_inf.v bug.ott
coqc bug.v
coqc bug_inf.v
```

and the output
```
Ott version 0.31   distribution of Mon 15 Jun 12:00:29 BST 2020
This is version 0.3.1 of LNgen.

File "./bug_inf.v", line 4752, characters 0-4:
Error:  (in proof lc_exp_abs_exists): Attempt to save an incomplete proof
```

The lemma that can't be shown by `lngen` is
```
Lemma lc_exp_abs_exists :
forall x1 T1 e1,
  lc_typ T1 ->
  lc_exp (open_exp_wrt_exp e1 (exp_var_f x1)) ->
  lc_exp (exp_abs T1 e1).
Proof.
intros; exp_lc_exists_tac; eauto with lngen.
Qed.
```

I am new to lngen and did not use a patched version of Ott since Ott appears to have the `-coq_lngen` now built in.

I am happy for any tipps and pointers.

**Comment by sweirich** [comment] 2020-11-23 14:04
Thanks for the bug report. I suspect the issue is that LNgen generated proof scripts haven't kept up with recent changes to Coq. (In my most recent use of LNgen, I had to patch up some of the proofs by hand.)

What version of Coq are you using?

Until this is addressed, a work around is to use the `--coq-no-proofs` flag so that LNgen doesn't even try to output proof scripts. This will also make your development cycle much faster.

**Comment by b-studios** [comment] 2020-11-23 18:10
Hey Stephanie, thanks a lot for your quick answer! I am currently using Coq `8.10.0` and I am happy to try out older versions and report back here.

**Comment by sweirich** [comment] 2020-11-23 22:16
Ok, I looked at the example more closely and maybe the trouble is the number of binders in the same term.  The proof fails with eauto level 5, but bumping it up to 6 makes it succeed.

**Comment by sweirich** [comment] 2020-11-23 22:42
Ok, I've created a new branch (https://github.com/plclub/lngen/tree/wip/issue4) that ups the eauto level enough to make this code pass. It will probably fail with four different binders.  I haven't checked yet to see if this version will work on other examples that I maintain, but it would be good to know whether it solves your problem.

**Comment by b-studios** [comment] 2020-11-24 19:52
Great, thanks! I will try it out tomorrow and report back here. I am pretty confident that, if it solved the MWE it will solve my problem.

Apart from that, it is a bit sad that the infrastructure code grows exponentially with the number of binders.
But I also don't know a solution, maybe besides using a kinded-system and only use two binders

**Comment by b-studios** [comment] 2020-11-25 18:09
Ok, I can confirm that your fix solved my problem also on a more realistic code base. (though the compilation times are quite long -- around 20-30min for the 17k infrastructure).

Thanks again!

**Comment by sweirich** [comment] 2022-03-09 20:01
FYI: I've merged this changed.

**Closed as completed by sweirich** 2022-03-09 20:01 UTC
